package constants

const (
	API_URL = "http://localhost:5000"

	ADMIN_EMAIL    = "admin@example.com"
	ADMIN_PASSWORD = "adminsecret"

	RESPONSE_TYPE_JSON = "json"

	TOKEN_TYPE_SIGNUP = "SIGNUP"

	ROLE_COMPANY_ADMIN     = "COMPANY_ADMIN"
	ROLE_COMPANY_DEVELOPER = "COMPANY_DEVELOPER"
	ROLE_COMPANY_OPERATOR  = "COMPANY_OPERATOR"

	ROLE_PLATFORM_ADMIN    = "PLATFORM_ADMIN"
	ROLE_PLATFORM_OPERATOR = "PLATFORM_OPERATOR"
	ROLE_PLATFORM_USER     = "PLATFORM_USER"
)
